"""内置样例数据。"""

from __future__ import annotations

from .models import SearchDocument


def _doc(
    slug: str,
    title: str,
    summary: str,
    content: str,
    tags: list[str],
    *,
    aliases: list[str] | None = None,
    entity_type: str = "",
    game_title: str = "",
    character_name: str = "",
    source_score: float = 0.7,
) -> SearchDocument:
    return SearchDocument(
        url=f"local://anime/{slug}",
        title=title,
        summary=summary,
        content=content,
        tags=tags,
        aliases=aliases or [],
        entity_type=entity_type,
        game_title=game_title,
        character_name=character_name,
        source_score=source_score,
        category="anime",
        source="sample",
        image_url="",
    )


SAMPLE_DOCUMENTS = [
    _doc(
        "frieren",
        "葬送的芙莉莲 角色与作品介绍",
        "《葬送的芙莉莲》讲述勇者一行打败魔王之后，精灵魔法使芙莉莲重新理解时间、离别与人的故事。",
        "芙莉莲是精灵魔法使，曾经与辛美尔、海塔、艾泽组成勇者小队。作品以旅行、公路片形式叙事和细腻情感见长。",
        ["动画", "角色", "芙莉莲", "辛美尔", "魔法", "奇幻"],
        aliases=["芙莉莲", "Frieren"],
        entity_type="character",
        character_name="芙莉莲",
        source_score=0.95,
    ),
    _doc(
        "elysia",
        "爱莉希雅 Elysia 角色资料",
        "爱莉希雅是《崩坏3》中的英桀角色，常被玩家称作爱莉，形象甜美、神秘且富有童话感。",
        "爱莉希雅与粉色妖精小姐相关，关键词包括乐土、英桀、弓箭、妖精、少女、浪漫。",
        ["游戏", "角色", "爱莉希雅", "爱莉", "崩坏3", "二次元"],
        aliases=["爱莉希雅", "Elysia", "爱莉"],
        entity_type="character",
        game_title="崩坏3",
        character_name="爱莉希雅",
        source_score=1.0,
    ),
    _doc(
        "miku",
        "初音未来 虚拟歌姬资料",
        "初音未来是 Crypton 推出的虚拟歌姬，也是二次元音乐文化的重要符号。",
        "初音未来拥有青绿色双马尾形象，活跃于 Vocaloid 音乐、演唱会、同人创作和游戏联动中。",
        ["虚拟歌姬", "音乐", "初音未来", "Vocaloid", "双马尾"],
        aliases=["初音未来", "初音", "Miku", "Hatsune Miku"],
        entity_type="character",
        character_name="初音未来",
        source_score=0.92,
    ),
    _doc(
        "madoka",
        "魔法少女小圆 作品介绍",
        "《魔法少女小圆》以魔法少女题材展开黑暗童话式叙事，鹿目圆、晓美焰等角色拥有很高讨论度。",
        "作品通过愿望、代价、轮回与命运讨论角色选择，适合搜索作品名、角色名和主题关键词。",
        ["动画", "魔法少女", "鹿目圆", "晓美焰", "丘比"],
        aliases=["魔法少女小圆", "小圆", "Madoka"],
        entity_type="work",
        game_title="",
        character_name="魔法少女小圆",
        source_score=0.9,
    ),
    _doc(
        "genshin",
        "原神 提瓦特开放世界",
        "《原神》是米哈游开发的开放世界游戏，玩家在提瓦特大陆探索七国与元素体系。",
        "角色包括荧、空、派蒙、钟离、雷电将军、纳西妲等，关键词包括抽卡、元素反应、二次元游戏。",
        ["游戏", "原神", "米哈游", "提瓦特", "开放世界", "派蒙"],
        aliases=["原神", "Genshin", "Genshin Impact"],
        entity_type="work",
        game_title="原神",
        source_score=1.0,
    ),
    _doc(
        "raiden-shogun",
        "雷电将军 原神角色资料",
        "雷电将军是《原神》稻妻地区的重要角色，与永恒、幕府、梦想一心和影相关。",
        "她的角色关键词包括稻妻、雷元素、神明、薙草之稻光、雷电影。",
        ["游戏", "原神", "雷电将军", "稻妻", "雷电影"],
        aliases=["雷电将军", "雷神", "影", "Raiden Shogun"],
        entity_type="character",
        game_title="原神",
        character_name="雷电将军",
        source_score=0.98,
    ),
    _doc(
        "nahida",
        "纳西妲 原神草神资料",
        "纳西妲是《原神》须弥地区的草神，小吉祥草王形象温柔聪慧。",
        "关键词包括须弥、智慧、梦境、草元素、布耶尔、净善宫。",
        ["游戏", "原神", "纳西妲", "草神", "须弥"],
        aliases=["纳西妲", "小草神", "Nahida", "布耶尔"],
        entity_type="character",
        game_title="原神",
        character_name="纳西妲",
        source_score=0.96,
    ),
    _doc(
        "star-rail",
        "崩坏：星穹铁道 开拓之旅",
        "《崩坏：星穹铁道》是米哈游银河冒险题材游戏，玩家乘坐星穹列车进行开拓。",
        "关键词包括开拓者、三月七、丹恒、姬子、瓦尔特、星神、命途和回合制战斗。",
        ["游戏", "崩坏星穹铁道", "星穹铁道", "开拓者", "三月七"],
        aliases=["崩坏：星穹铁道", "星穹铁道", "Honkai Star Rail"],
        entity_type="work",
        game_title="崩坏：星穹铁道",
        source_score=0.98,
    ),
    _doc(
        "march-7th",
        "三月七 星穹铁道角色资料",
        "三月七是《崩坏：星穹铁道》的核心伙伴，活泼、爱拍照，并使用冰属性力量。",
        "她与开拓者、丹恒组成列车组早期冒险队伍，关键词包括相机、冰、记忆和少女。",
        ["游戏", "三月七", "星穹铁道", "开拓者", "冰属性"],
        aliases=["三月七", "March 7th", "Mar.7th"],
        entity_type="character",
        game_title="崩坏：星穹铁道",
        character_name="三月七",
        source_score=0.95,
    ),
    _doc(
        "arknights",
        "明日方舟 罗德岛档案",
        "《明日方舟》是鹰角网络开发的塔防策略游戏，故事围绕罗德岛、感染者和泰拉世界展开。",
        "关键词包括博士、阿米娅、凯尔希、源石、干员、整合运动、塔防。",
        ["游戏", "明日方舟", "罗德岛", "阿米娅", "塔防"],
        aliases=["明日方舟", "Arknights"],
        entity_type="work",
        game_title="明日方舟",
        source_score=0.97,
    ),
    _doc(
        "amiya",
        "阿米娅 明日方舟角色资料",
        "阿米娅是《明日方舟》中罗德岛的公开领袖，温柔坚定，是博士最重要的伙伴之一。",
        "角色关键词包括术师、奇美拉、罗德岛、感染者、领袖和责任。",
        ["游戏", "阿米娅", "明日方舟", "罗德岛", "术师"],
        aliases=["阿米娅", "Amiya"],
        entity_type="character",
        game_title="明日方舟",
        character_name="阿米娅",
        source_score=0.96,
    ),
    _doc(
        "blue-archive",
        "蔚蓝档案 基沃托斯学园都市",
        "《蔚蓝档案》以学园都市基沃托斯为舞台，玩家作为老师与学生们解决事件。",
        "关键词包括老师、学生、阿罗娜、白子、日奈、学园、青春和日常。",
        ["游戏", "蔚蓝档案", "Blue Archive", "白子", "阿罗娜"],
        aliases=["蔚蓝档案", "Blue Archive"],
        entity_type="work",
        game_title="蔚蓝档案",
        source_score=0.9,
    ),
    _doc(
        "genshin-version-news",
        "原神 最新版本活动资讯",
        "整理原神近期版本、限时活动、卡池轮换和官方公告，适合查询最新活动或版本更新。",
        "本条样例用于验证资讯意图排序：当用户搜索最新活动、版本、公告、新闻时，news 类型结果应该比总览页更靠前。",
        ["游戏", "资讯", "原神", "最新活动", "版本更新", "公告"],
        aliases=["原神活动", "原神版本", "最新活动"],
        entity_type="news",
        game_title="原神",
        source_score=0.86,
    ),
    _doc(
        "star-rail-version-news",
        "星穹铁道 版本活动与更新公告",
        "汇总崩坏：星穹铁道版本活动、跃迁卡池、活动奖励和更新公告。",
        "当查询星穹铁道活动、版本、最新公告时，这类新闻文档应优先承接资讯需求。",
        ["游戏", "资讯", "星穹铁道", "版本活动", "更新公告"],
        aliases=["星穹铁道活动", "星穹铁道版本", "崩铁活动"],
        entity_type="news",
        game_title="崩坏：星穹铁道",
        source_score=0.84,
    ),
    _doc(
        "cosplay",
        "Cosplay 二次元角色扮演",
        "Cosplay 是围绕动漫、游戏、漫画角色进行服装、妆造、摄影和舞台表达的创作活动。",
        "搜索 coser、漫展、角色服、道具、妆容、摄影棚等关键词时，可以归入二次元文化资料。",
        ["cosplay", "coser", "漫展", "角色扮演", "摄影"],
        aliases=["Cosplay", "Coser"],
        entity_type="news",
        source_score=0.7,
    ),
    _doc(
        "saber",
        "Saber 阿尔托莉雅 Fate 系列",
        "Saber 阿尔托莉雅是 Fate 系列代表角色，常见关键词包括圣杯战争、骑士王、Excalibur。",
        "她在《Fate/stay night》等作品中登场，角色形象融合骑士精神、王道叙事和英灵设定。",
        ["动画", "游戏", "Saber", "阿尔托莉雅", "Fate", "圣杯战争"],
        aliases=["Saber", "阿尔托莉雅", "Artoria", "Arthuria"],
        entity_type="character",
        game_title="Fate",
        character_name="阿尔托莉雅",
        source_score=0.97,
    ),
    _doc(
        "asuna",
        "亚丝娜 刀剑神域角色资料",
        "亚丝娜是《刀剑神域》的核心角色之一，拥有闪光称号，与桐人共同经历虚拟世界冒险。",
        "作品关键词包括 SAO、艾恩葛朗特、VRMMO、攻略组、细剑、结城明日奈。",
        ["动画", "亚丝娜", "刀剑神域", "桐人", "SAO"],
        aliases=["亚丝娜", "Asuna", "结城明日奈"],
        entity_type="character",
        game_title="刀剑神域",
        character_name="亚丝娜",
        source_score=0.96,
    ),
    _doc(
        "mikasa",
        "三笠·阿克曼 进击的巨人",
        "三笠·阿克曼是《进击的巨人》主要角色，以强大战斗力、围巾和阿克曼血统为核心记忆点。",
        "她与艾伦、阿尔敏一起成长，故事包含巨人、城墙、自由、战争和命运等主题。",
        ["动画", "三笠", "进击的巨人", "艾伦", "阿克曼"],
        aliases=["三笠", "Mikasa", "三笠·阿克曼"],
        entity_type="character",
        game_title="进击的巨人",
        character_name="三笠·阿克曼",
        source_score=0.95,
    ),
    _doc(
        "nezuko",
        "祢豆子 鬼灭之刃角色资料",
        "祢豆子是《鬼灭之刃》中炭治郎的妹妹，变成鬼后仍保有人性与亲情。",
        "关键词包括竹筒、鬼、血鬼术、灶门兄妹、无限列车、花江夏树、吾峠呼世晴。",
        ["动画", "祢豆子", "鬼灭之刃", "炭治郎", "鬼"],
        aliases=["祢豆子", "Nezuko"],
        entity_type="character",
        game_title="鬼灭之刃",
        character_name="祢豆子",
        source_score=0.96,
    ),
    _doc(
        "anya",
        "阿尼亚 间谍过家家角色资料",
        "阿尼亚是《间谍过家家》中的超能力少女，读心能力和可爱表情包让她广受欢迎。",
        "她与劳埃德、约尔组成临时家庭，作品融合间谍、校园、家庭喜剧和日常治愈元素。",
        ["动画", "阿尼亚", "间谍过家家", "读心", "约尔"],
        aliases=["阿尼亚", "Anya"],
        entity_type="character",
        game_title="间谍过家家",
        character_name="阿尼亚",
        source_score=0.97,
    ),
    _doc(
        "kaguya",
        "辉夜大小姐想让我告白",
        "《辉夜大小姐想让我告白》是校园恋爱喜剧，围绕四宫辉夜与白银御行的恋爱头脑战展开。",
        "作品关键词包括学生会、告白、藤原千花、早坂爱、恋爱喜剧、校园日常。",
        ["动画", "辉夜大小姐", "四宫辉夜", "白银御行", "恋爱喜剧"],
        aliases=["辉夜大小姐", "Kaguya-sama"],
        entity_type="work",
        game_title="",
        character_name="",
        source_score=0.9,
    ),
    _doc(
        "konosuba",
        "为美好的世界献上祝福",
        "《为美好的世界献上祝福》是异世界喜剧作品，佐藤和真、阿库娅、惠惠和达克妮丝组成问题小队。",
        "关键词包括爆裂魔法、阿库娅、惠惠、异世界、搞笑、冒险者。",
        ["动画", "素晴", "惠惠", "阿库娅", "爆裂魔法"],
        aliases=["为美好的世界献上祝福", "素晴", "KonoSuba"],
        entity_type="work",
        game_title="",
        character_name="",
        source_score=0.9,
    ),
    _doc(
        "k-on",
        "轻音少女 K-ON!",
        "《轻音少女》描写樱丘高中轻音部的日常、音乐和友情，是日常系动画代表作之一。",
        "平泽唯、秋山澪、田井中律、琴吹紬、中野梓组成乐队，放学后茶会氛围浓厚。",
        ["动画", "轻音少女", "K-ON", "平泽唯", "秋山澪", "音乐"],
        aliases=["轻音少女", "K-ON"],
        entity_type="work",
        source_score=0.9,
    ),
    _doc(
        "clannad",
        "CLANNAD 家族与校园故事",
        "《CLANNAD》由 Key 视觉小说改编，动画以校园、家庭、成长和亲情为核心。",
        "冈崎朋也、古河渚、藤林杏、坂上智代等角色构成催泪群像，After Story 尤其知名。",
        ["动画", "CLANNAD", "古河渚", "冈崎朋也", "催泪", "Key"],
        aliases=["CLANNAD"],
        entity_type="work",
        source_score=0.9,
    ),
    _doc(
        "steins-gate",
        "命运石之门 Steins;Gate",
        "《命运石之门》围绕时间机器、世界线和中二科学家冈部伦太郎展开。",
        "牧濑红莉栖、椎名真由理、桶子等角色推动故事，关键词包括时间跳跃、平行世界线、凤凰院凶真。",
        ["动画", "游戏", "命运石之门", "牧濑红莉栖", "时间旅行"],
        aliases=["命运石之门", "Steins;Gate"],
        entity_type="work",
        source_score=0.92,
    ),
    _doc(
        "eva",
        "新世纪福音战士 EVA",
        "《新世纪福音战士》是机甲、心理、宗教符号和青春创伤交织的经典动画。",
        "碇真嗣、绫波丽、明日香、葛城美里与使徒战斗，作品讨论孤独、自我和人与人的边界。",
        ["动画", "EVA", "绫波丽", "明日香", "机甲", "庵野秀明"],
        aliases=["EVA", "Neon Genesis Evangelion"],
        entity_type="work",
        source_score=0.93,
    ),
    _doc(
        "haruhi",
        "凉宫春日的忧郁",
        "《凉宫春日的忧郁》围绕 SOS 团、外星人、未来人、超能力者和普通人阿虚展开。",
        "凉宫春日、长门有希、朝比奈实玖瑠、古泉一树共同构成校园科幻喜剧。",
        ["动画", "凉宫春日", "长门有希", "SOS团", "京都动画"],
        aliases=["凉宫春日的忧郁", "凉宫春日"],
        entity_type="work",
        source_score=0.9,
    ),
    _doc(
        "your-name",
        "你的名字 新海诚动画电影",
        "《你的名字》是新海诚导演的动画电影，讲述立花泷和宫水三叶之间跨越时间与空间的相遇。",
        "关键词包括身体互换、彗星、羁绊、乡镇、都市、RADWIMPS 和青春恋爱。",
        ["动画电影", "你的名字", "新海诚", "宫水三叶", "立花泷"],
        aliases=["你的名字", "君の名は。", "Your Name"],
        entity_type="work",
        source_score=0.92,
    ),
    _doc(
        "weathering-with-you",
        "天气之子 新海诚作品",
        "《天气之子》讲述森岛帆高与天野阳菜在雨季东京相遇的故事。",
        "作品关键词包括晴女、东京、天气、选择、青春、RADWIMPS。",
        ["动画电影", "天气之子", "新海诚", "天野阳菜", "晴女"],
        aliases=["天气之子", "天气の子", "Weathering With You"],
        entity_type="work",
        source_score=0.91,
    ),
    _doc(
        "holo",
        "hololive 虚拟主播资料",
        "hololive 是知名虚拟主播企划，成员以直播、音乐、游戏实况和二次创作为核心活动。",
        "相关关键词包括 VTuber、虚拟主播、直播、歌回、剪辑、同人文化。",
        ["虚拟主播", "VTuber", "hololive", "直播", "音乐"],
        aliases=["hololive", "HoloLive"],
        entity_type="news",
        source_score=0.8,
    ),
    _doc(
        "cosplay",
        "Cosplay 二次元角色扮演",
        "Cosplay 是围绕动漫、游戏、漫画角色进行服装、妆造、摄影和舞台表达的创作活动。",
        "搜索 coser、漫展、角色服、道具、妆容、摄影棚等关键词时，可以归入二次元文化资料。",
        ["cosplay", "coser", "漫展", "角色扮演", "摄影"],
        aliases=["Cosplay", "Coser"],
        entity_type="news",
        source_score=0.7,
    ),
]
